# Generated by Django 6.0 on 2025-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.ImageField(blank=True, default='image/car-2.png', upload_to='media/')),
                ('cat_tilte', models.CharField(max_length=200)),
                ('cat_rate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Centalfeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_icon', models.CharField(max_length=200)),
                ('feat_title', models.CharField(max_length=200)),
                ('feat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Centalprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=200)),
                ('pro_number', models.CharField(max_length=200)),
                ('pro_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_icon', models.CharField(max_length=200)),
                ('num_counter', models.CharField(max_length=200)),
                ('num_title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_image', models.ImageField(blank=True, default='image/car-3.png', upload_to='media/')),
                ('review_title', models.CharField(max_length=200)),
                ('review_icon', models.CharField(max_length=200)),
                ('review_desc', models.TextField()),
            ],
        ),
    ]
