# Generated by Django 6.0 on 2025-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0005_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subjects',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='your_projects',
            field=models.CharField(max_length=200),
        ),
    ]
